export const PRODUCT_DETAILS_FETCHING_REQUEST = "PRODUCT_DETAILS_FETCHING_REQUEST";
export const PRODUCT_DETAILS_FETCHING_SUCCESS = "PRODUCT_DETAILS_FETCHING_SUCCESS";
export const PRODUCT_DETAILS_FETCHING_FAILURE = "PRODUCT_DETAILS_FETCHING_FAILURE";